module Seckcoin
  PERFORM_ERROR = 'I do not understand that command. Try "help"'
  BALANCE_REPLY_PRETEXT = 'Your balance: '
  CURRENCY_ICON = ':skc:'
  WEALTHY_UPPER_BOUND = 1000
  WEALTHY_UPPER_BOUND_POSTTEXT = ' very wealthy!'
  WEALTHY_UPPER_BOUND_EMOJI = ':moneybag:'
  BALANCE_REPLY_POSTTEXT = ' SecKCoins'
  DEPOSIT_PRETEXT = 'This is your :skc: address'
  DEPOSIT_POSTTEXT = ', you can deposit directly to it'
  TIP_ERROR_TEXT = 'Syntax is: tip @username amount'
  TIP_PRETEXT = ':money_with_wings:'
  TIP_POSTTEXT1 = 'https://seckco.in/tx/'
  ADDRESS_LOOKUP = 'https://seckco.in/address/'
  TIP_POSTTEXT2 = '|blockchain'
  TIP_POSTTEXT3 = '|Address'
  WITHDRAW_TEXT = ':SKC: TRANSFER INITITIATED'
  WITHDRAW_ICON = ':classical_building:'
  NETWORKINFO_ICON = ':bar_chart:'
  TOO_POOR_TEXT = 'Sory, your to pour'
  NO_PURPOSE_LOWER_BOUND_TEXT = 'Transactions need to be greater than 0.001, MAKE IT RAIN!'
  NO_PURPOSE_LOWER_BOUND = 0.001
  HELP_TEXT = 'Commands I understand are: '
  RANDOMIZED_EMOJI = ':black_joker:'
  NETWORK = 'seckcoin'
end
